# 模型配置
model:
  type: "Autoencoder"
  params:
    in_channels: 1
    base_channels: 16
    latent_dim: 64

# 训练参数
training:
  epochs: 150
  lr: 0.001
  save_interval: 15
  early_stop: True
  patience: 10
  monitor: "val_loss"
  batch_size: 32

# 数据配置引用
data_config: "configs/data_config.yaml"