# 模型配置
model:
  type: "MiniUNet"
  params:
    in_channels: 1
    base_channels: 32  # 控制模型容量

# 训练参数
training:
  epochs: 200
  lr: 0.001
  save_interval: 25
  early_stop: True
  patience: 25
  monitor: "ssim"  # 推荐监控SSIM

# 数据配置引用
data_config: "configs/data_config.yaml"