# configs/train_config.yaml
data_dir: "E:\\workspace\\class_101\\COVID_Enhancement\\miniunet_improved\\data\\COVID-19_Radiography_Dataset"
log_dir: 'outputs/logs'
batch_size: 16      # 原为8
lr: 0.002           # 原为0.001 (+100%)
weight_decay: 0.01  # 新增参数
epochs: 80          # 适当增加总epoch
use_scheduler: True # 启用学习率调度
patience: 5